# Generated by Django 4.2.27 on 2026-01-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullstackresources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='url',
            field=models.CharField(default='#', max_length=2000, unique=True),
            preserve_default=False,
        ),
    ]
