# Generated by Django 4.2.27 on 2026-01-22 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fullstackresources', '0002_resource_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='url',
            new_name='link',
        ),
    ]
