# Generated by Django 4.2.27 on 2026-01-23 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullstackresources', '0003_rename_url_resource_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='link',
            field=models.URLField(max_length=2000, unique=True),
        ),
    ]
