# Generated by Django 4.2.27 on 2026-01-23 04:50

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('fullstackresources', '0004_alter_resource_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), name='resource_title_ci_unique'),
        ),
    ]
